### PR TITLE
Openshift write permission DEVOPS-481

### PR DESCRIPTION
**Pull request by terovirtanen**

### CODE REVIEW

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr447.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr447.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr447.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr447.dev.hel.ninja** :rocket::rocket::rocket:

**Review by mikkovihonen — APPROVED** [review]

**Pull request merged**
