### PR TITLE
fix: summer trailer texts for 2023

### PR DESCRIPTION
**Pull request by melniiv**

### CODE REVIEW

**Review by nikomakela — APPROVED** [review]

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr454.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr454.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr454.dev.hel.ninja** :rocket::rocket::rocket:

**Comment by terovirtanen** [comment]
**Venepaikat-customer-ui branch is deployed to platta: https://venepaikat-customer-ui-pr454.dev.hel.ninja** :rocket::rocket::rocket:

**Pull request merged**
